services:
  - type: web
    name: usmef-news-report
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --timeout 120 app:app
    autoDeployTrigger: commit
